name: dwt_lhj
version: 0.0.1
description: Some missing widgets and utilities I use from DWT, like client side routing, html lists and data table library
author: Lateef Jackson <lateef.jackson@gmail.com>
homepage: https://github.com/lateefj/dwt_lhj
dependencies:
  browser: any
  logging: any
  dart_web_toolkit: '>=0.3.0'
